### ISSUE TITLE
Code first approach

### ISSUE THREAD

**Issue by russellhoff** [revinate/jaxws-spring#1]
Hi!

I'm new to Spring Framework. Thankfully, I discovered Spring Boot and I've started coding stuff using it.

I want to develop a web service using JAX-WS, so this repo will help me out a lot. What I've seen is that the approach you are following is contract-first (as far as I know), starting from the wsdl.

Is there a simple way to make this work with code-first? I'm trying to figure a Hello World WS out.

Thanks for your work.

**Comment by alexleigh** [comment]
Fortunately the Java-first approach in JAX-WS is much simpler than the WSDL-first approach. I have added a Java-first sample at https://github.com/revinate/jaxws-spring/tree/master/jaxws-spring-sample-fromjava. You can run this sample by executing `./gradlew :jaxws-spring-sample-fromjava:bootRun` in the project root directory. Hope this helps!

**Comment by russellhoff** [comment]
Thank you so much @alexleigh !
